/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostDTO = IDL.Record({
  'id' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const NotificationContent = IDL.Variant({
  'like' : IDL.Record({ 'postId' : IDL.Text }),
  'comment' : IDL.Record({ 'comment' : Comment, 'postId' : IDL.Text }),
  'follow' : IDL.Record({ 'followerId' : IDL.Principal }),
});
export const Notification = IDL.Record({
  'content' : NotificationContent,
  'timestamp' : IDL.Int,
});
export const UserProfileDTO = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'notifications' : IDL.Vec(Notification),
  'followers' : IDL.Vec(IDL.Principal),
  'following' : IDL.Vec(IDL.Principal),
  'profilePic' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [IDL.Text],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PostDTO)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileDTO)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(PostDTO)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostDTO)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileDTO)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileDTO], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostDTO = IDL.Record({
    'id' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const NotificationContent = IDL.Variant({
    'like' : IDL.Record({ 'postId' : IDL.Text }),
    'comment' : IDL.Record({ 'comment' : Comment, 'postId' : IDL.Text }),
    'follow' : IDL.Record({ 'followerId' : IDL.Principal }),
  });
  const Notification = IDL.Record({
    'content' : NotificationContent,
    'timestamp' : IDL.Int,
  });
  const UserProfileDTO = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'notifications' : IDL.Vec(Notification),
    'followers' : IDL.Vec(IDL.Principal),
    'following' : IDL.Vec(IDL.Principal),
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [IDL.Text],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PostDTO)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileDTO)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(PostDTO)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostDTO)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileDTO)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileDTO], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };