/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Notification {
  'content' : NotificationContent,
  'timestamp' : bigint,
}
export type NotificationContent = { 'like' : { 'postId' : string } } |
  { 'comment' : { 'comment' : Comment, 'postId' : string } } |
  { 'follow' : { 'followerId' : Principal } };
export interface PostDTO {
  'id' : string,
  'hashtags' : Array<string>,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface UserProfileDTO {
  'bio' : string,
  'username' : string,
  'notifications' : Array<Notification>,
  'followers' : Array<Principal>,
  'following' : Array<Principal>,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, Array<string>, ExternalBlob], string>,
  'deletePost' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllPosts' : ActorMethod<[], Array<PostDTO>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileDTO]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getLikeCount' : ActorMethod<[string], bigint>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[string], [] | [PostDTO]>,
  'getPostsByUser' : ActorMethod<[Principal], Array<PostDTO>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileDTO]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileDTO], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];